# Generated by Django 4.0.6 on 2022-12-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.TextField(max_length=255)),
                ('sector', models.TextField(max_length=255)),
                ('available', models.CharField(default='a', max_length=10)),
            ],
        ),
    ]
